# Generated by Django 4.2.16 on 2024-12-29 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cliente',
            table='home_cliente',
        ),
    ]
