# Generated by Django 4.2.16 on 2024-12-13 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='estoque',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
